# TODO add comments and sections to the config file for better overview
do_classification: true
num_categories: 3
useGyro: true
train_days: ['day3', 'day9', 'day28', 'day90', 'day365']
val_days: ['day3', 'day9', 'day28', 'day90', 'day365']
normalize: true
exclude_p_pats: 0.2
batch_size: 64
shuffle: true
num_workers: 1
dropout: 0.3
learning_rate: 1e-3
weight_decay: 1e-4
hidden_dim: 32
projection_dim: 32
num_layers: 3
augment_prob: 0.75
noise_level: 0.1
mask_ratio: 0.3
n_splits: 5
mc_samples: 10
n_shuffleSegments: 5
temperature: 0.07
sample_strat: 'diff_sample'
p_components: 5
train_adversary: false
logName: "SimCLR_experiments_one_wrist"
train_one_wrist: false